config/routes.rb
Rails.application.routes.draw do
  resources :icecreams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'icecreams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flavor.rb
class Flavor < ApplicationRecord
end

app/models/icecream.rb
class Icecream < ApplicationRecord
  FLAVORS = ["vanilla","chocolate","strawberry","pistachio"]
  SIZES = ["pint","quart","gallon"]
  validates :flavor, presence: true
  validates :size, presence: true
  validates :count, presence: true
  validates :name, presence: true
  validates :count, numericality: { greater_than_or_equal_to: 1}

  def self.flavors
    two_d = []
    FLAVORS.each do |f|
      two_d << [f,f]
    end
    return two_d
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
  before_action :set_icecream, only: [:show, :edit, :update, :destroy]

  # GET /icecreams
  # GET /icecreams.json
  def index
    @icecreams = Icecream.all
  end

  # GET /icecreams/1
  # GET /icecreams/1.json
  def show
  end

  # GET /icecreams/new
  def new
    @icecream = Icecream.new
  end

  # GET /icecreams/1/edit
  def edit
  end

  # POST /icecreams
  # POST /icecreams.json
  def create
    @icecream = Icecream.new(icecream_params)

    respond_to do |format|
      if @icecream.save
        format.html { redirect_to @icecream, notice: 'The ice cream order was successfully created.' }
        format.json { render :show, status: :created, location: @icecream }
      else
        format.html { render :new }
        format.json { render json: @icecream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icecreams/1
  # PATCH/PUT /icecreams/1.json
  def update
    respond_to do |format|
      if @icecream.update(icecream_params)
        format.html { redirect_to @icecream, notice: 'The ice cream order was successfully updated.' }
        format.json { render :show, status: :ok, location: @icecream }
      else
        format.html { render :edit }
        format.json { render json: @icecream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icecreams/1
  # DELETE /icecreams/1.json
  def destroy
    @icecream.destroy
    respond_to do |format|
      format.html { redirect_to icecreams_url, notice: 'The ice cream order was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icecream
      @icecream = Icecream.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def icecream_params
      params.require(:icecream).permit(:name, :count, :flavor, :size, :new_account)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icecreams_helper.rb
module IcecreamsHelper
end

app/views/icecreams/_form.html.erb
<%= form_with(model: icecream, local: true) do |form| %>
  <% if icecream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(icecream.errors.count, "error") %> prohibited this icecream from being saved:</h2>

      <ul>
      <% icecream.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <!--
    <div class="field">
    <% #form.label :flavor %>
    <% #form.select(:flavor, Icecream.flavors) %>
  </div>
  -->
  <div class="field">
    <%= form.label :flavor %>
    <%= form.collection_select :flavor, Flavor.all, :name, :name, {selected: icecream.flavor} %>
  </div>

  <div class="field">
    <%= form.label :size %><br>
    <% Icecream::SIZES.each do |s| %>
      <%= form.radio_button :size, s %>
      <%= form.label :size, s, value: s, class: "checkbox-label" %><br>
    <% end %>
  </div>

  <div class="field">
    <%= form.check_box :new_account %>
      <%= form.label :new_account, class: "checkbox-label" %><br>
  </div>

  <div class="actions">
    <%= form.submit value: @submit_text, "data-disable-with" => @submit_text, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/icecreams/edit.html.erb
<h1>Edit Order</h1>
<% @submit_text = "Update Order" %>

<%= render 'form', icecream: @icecream %>

<%= link_to 'Show', @icecream, class: "btn btn-primary" %>

app/views/icecreams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ice Cream Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>Flavor</th>
      <th>Size</th>
      <th>New account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @icecreams.each do |icecream| %>
      <tr>
        <td><%= icecream.name %></td>
        <td><%= icecream.count %></td>
        <td><%= icecream.flavor %></td>
        <td><%= icecream.size %></td>
        <td><%= icecream.new_account %></td>
        <td><%= link_to 'Show', icecream, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_icecream_path(icecream), class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', icecream, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/icecreams/new.html.erb
<h1>New Order</h1>
<% @submit_text = "Create Order" %>

<%= render 'form', icecream: @icecream %>

app/views/icecreams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @icecream.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @icecream.count %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @icecream.flavor %>
</p>

<p>
  <strong>Size:</strong>
  <%= @icecream.size %>
</p>

<p>
  <strong>New account:</strong>
  <%= @icecream.new_account %>
</p>

<%= link_to 'Edit', edit_icecream_path(@icecream), class: "btn btn-primary" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ice Cream Orders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%= icecreams_path %>">Ice Cream Orders<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_icecream_path %>">New Order</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>
      <div class="icforms">
        <%= yield %>
      </div>
    </main>
  </body>
</html>